version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: produtosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - produtos-network

  api:
    build: .
    container_name: produtos_api
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - produtos-network

volumes:
  postgres_data:

networks:
  produtos-network:
